import { ethers, Contract } from "ethers";
import { provider, signer, getAddresses } from "../config/blockchain";
import { TransferEvent } from "../types";

// ABI imports — these are minimal ABIs for the deployed contracts.
// Full ABIs should be generated by Hardhat's compilation artifacts.

const FARMER_REGISTRY_ABI = [
  "function registerFarmer(string farmerId, string name, string location, string cropTypes, bytes32 aadhaarHash) external",
  "function verifyFarmer(string farmerId) external",
  "function getFarmer(string farmerId) external view returns (tuple(string farmerId, string name, string location, string cropTypes, bytes32 aadhaarHash, bool isVerified, uint256 registeredAt))",
  "function isFarmerVerified(string farmerId) external view returns (bool)",
];

const BATCH_TRACKER_ABI = [
  "function createBatch(string batchId, string farmerId, string herbName, string harvestLocation, uint256 harvestDate, string quantity, string ipfsDocHash) external",
  "function transferBatch(string batchId, uint8 newStage, string actorId, string notes, string newIpfsHash) external",
  "function certifyBatch(string batchId, string certDocHash) external",
  "function getBatch(string batchId) external view returns (tuple(string batchId, string farmerId, string herbName, string harvestLocation, uint256 harvestDate, string quantity, uint8 currentStage, bool isCertified, string ipfsDocHash, uint256 createdAt))",
  "function getBatchHistory(string batchId) external view returns (tuple(uint8 stage, address actorAddress, string actorId, string notes, string ipfsHash, uint256 timestamp)[])",
  "function getBatchStage(string batchId) external view returns (uint8)",
];

const CERTIFICATION_ABI = [
  "function issueCertificate(string certId, string batchId, string certifierOrgName, string certType, string ipfsCertHash, uint256 expiresAt) external",
  "function getCertificates(string batchId) external view returns (tuple(string certId, string batchId, address issuedBy, string certifierOrgName, string certType, string ipfsCertHash, uint256 issuedAt, uint256 expiresAt, bool isRevoked)[])",
  "function isBatchCertified(string batchId) external view returns (bool)",
];

function getContracts() {
  const addresses = getAddresses();
  return {
    farmerRegistry: new Contract(addresses.FarmerRegistry, FARMER_REGISTRY_ABI, signer),
    batchTracker: new Contract(addresses.BatchTracker, BATCH_TRACKER_ABI, signer),
    certification: new Contract(addresses.Certification, CERTIFICATION_ABI, signer),
  };
}

/**
 * Register a farmer on-chain.
 * @returns Transaction hash
 */
export async function registerFarmerOnChain(
  farmerId: string,
  name: string,
  location: string,
  cropTypes: string,
  aadhaarHash: string
): Promise<string> {
  try {
    const { farmerRegistry } = getContracts();
    const hashedAadhaar = ethers.keccak256(ethers.toUtf8Bytes(aadhaarHash));
    const tx = await farmerRegistry.registerFarmer(farmerId, name, location, cropTypes, hashedAadhaar);
    const receipt = await tx.wait();
    return receipt.hash;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown blockchain error";
    console.error(JSON.stringify({ service: "blockchainService", fn: "registerFarmerOnChain", error: message }));
    throw new Error(`Blockchain error: ${message}`);
  }
}

/**
 * Create a batch on-chain.
 * @returns Transaction hash
 */
export async function createBatchOnChain(
  batchId: string,
  farmerId: string,
  herbName: string,
  harvestLocation: string,
  harvestDate: number,
  quantity: string,
  ipfsHash: string
): Promise<string> {
  try {
    const { batchTracker } = getContracts();
    const tx = await batchTracker.createBatch(batchId, farmerId, herbName, harvestLocation, harvestDate, quantity, ipfsHash);
    const receipt = await tx.wait();
    return receipt.hash;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown blockchain error";
    console.error(JSON.stringify({ service: "blockchainService", fn: "createBatchOnChain", error: message }));
    throw new Error(`Blockchain error: ${message}`);
  }
}

/**
 * Transfer a batch to a new supply chain stage.
 * @returns Transaction hash
 */
export async function transferBatchOnChain(
  batchId: string,
  newStage: number,
  actorId: string,
  notes: string,
  ipfsHash: string
): Promise<string> {
  try {
    const { batchTracker } = getContracts();
    const tx = await batchTracker.transferBatch(batchId, newStage, actorId, notes, ipfsHash);
    const receipt = await tx.wait();
    return receipt.hash;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown blockchain error";
    console.error(JSON.stringify({ service: "blockchainService", fn: "transferBatchOnChain", error: message }));
    throw new Error(`Blockchain error: ${message}`);
  }
}

/**
 * Get the full history of a batch from on-chain events.
 */
export async function getBatchHistoryFromChain(batchId: string): Promise<TransferEvent[]> {
  try {
    const { batchTracker } = getContracts();
    const raw = await batchTracker.getBatchHistory(batchId);
    return raw.map((e: any) => ({
      stage: Number(e.stage),
      actorAddress: e.actorAddress,
      actorId: e.actorId,
      notes: e.notes,
      ipfsHash: e.ipfsHash,
      timestamp: new Date(Number(e.timestamp) * 1000).toISOString(),
    }));
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown blockchain error";
    console.error(JSON.stringify({ service: "blockchainService", fn: "getBatchHistoryFromChain", error: message }));
    throw new Error(`Blockchain error: ${message}`);
  }
}

/**
 * Issue a certificate on-chain.
 * @returns Transaction hash
 */
export async function issueCertOnChain(
  certId: string,
  batchId: string,
  orgName: string,
  certType: string,
  ipfsHash: string,
  expiresAt: number
): Promise<string> {
  try {
    const { certification } = getContracts();
    const tx = await certification.issueCertificate(certId, batchId, orgName, certType, ipfsHash, expiresAt);
    const receipt = await tx.wait();
    return receipt.hash;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown blockchain error";
    console.error(JSON.stringify({ service: "blockchainService", fn: "issueCertOnChain", error: message }));
    throw new Error(`Blockchain error: ${message}`);
  }
}
